"""
SDD scaffolding: generate the skill + conformance test stubs for a new feature.

Usage::

    python scripts/specify_new_feature.py rsi-strategy-gate
    python scripts/specify_new_feature.py weekly-drawdown-alert --group risk
    python scripts/specify_new_feature.py manual-name --number 35

The script picks the next free skill number (skipping Phase 2
reservations 20–27, per the docs/skills/README.md inventory) and
creates two files:

    docs/skills/NN_short_name.md
        Filled from _template.md with the feature name substituted
        into headers + the "Last verified" footer dated to today.
        §1-§5 still need human/LLM authoring before any code is
        written.

    tests/conformance/test_skill_NN_short_name.py
        A failing skeleton conformance test. Importing succeeds
        but every assertion raises ``NotImplementedError`` so
        ``pytest tests/conformance/`` immediately flunks until the
        author replaces the stubs with real assertions tied to the
        skill's §2 / §4.

This forces the SDD flow: spec → failing test → code that makes the
test pass → re-stamp footer. It's not strictly required (CLAUDE.md
covers the conventions), but having a script means a human or AI
contributor can't accidentally skip the spec-first step by writing
the code first.

Run from the repo root.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path
from typing import Set

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = REPO_ROOT / "docs" / "skills"
TEMPLATE_PATH = SKILLS_DIR / "_template.md"
CONFORMANCE_DIR = REPO_ROOT / "tests" / "conformance"

# Phase 2 reserved numbers — see docs/skills/README.md. Skipping these
# avoids collisions with already-planned skill slots.
PHASE_2_RESERVED: Set[int] = {20, 21, 22, 23, 24, 25, 26, 27}

VALID_GROUPS = {
    "strategy", "regime", "bias", "data_quality",
    "risk", "architecture", "meta",
}


def next_free_number() -> int:
    """Return the next unused skill number, skipping Phase 2 reservations."""
    used: Set[int] = set()
    for sf in SKILLS_DIR.glob("[0-9][0-9]_*.md"):
        m = re.match(r"(\d{2})_", sf.name)
        if m:
            used.add(int(m.group(1)))
    for n in range(28, 100):
        if n in used or n in PHASE_2_RESERVED:
            continue
        return n
    raise RuntimeError("No free skill number under 100 — extend the range.")


def kebab_to_snake(name: str) -> str:
    """rsi-strategy-gate → rsi_strategy_gate."""
    return name.replace("-", "_").lower()


def kebab_to_title(name: str) -> str:
    """rsi-strategy-gate → RSI Strategy Gate (initial caps with acronym preserve)."""
    parts = name.split("-")
    acronyms = {"rsi", "vix", "iv", "atr", "adx", "ev", "cw", "pop",
                "dte", "occ", "spx", "spy", "spdr", "etf", "api",
                "llm", "ui", "ux", "pdt", "oauth", "nbbo", "ic", "mr"}
    out = []
    for p in parts:
        out.append(p.upper() if p.lower() in acronyms else p.capitalize())
    return " ".join(out)


def render_skill_stub(number: int, name_kebab: str, group: str) -> str:
    """Build the skill markdown by substituting placeholders in _template.md."""
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    title = kebab_to_title(name_kebab)
    today = date.today().isoformat()

    # Substitutions are conservative — only the placeholders we know about.
    out = template
    out = out.replace("# <Skill Name>", f"# {title}")
    out = out.replace(
        "Phase:** 1 | 2",
        "Phase:** 1",
    )
    out = out.replace(
        "Group:** strategy / regime / bias / data_quality / risk / architecture",
        f"Group:** {group}",
    )
    out = out.replace(
        "*Last verified against repo HEAD on YYYY-MM-DD.*",
        f"*Last verified against repo HEAD on {today}.*",
    )
    # Add a clear "STUB — fill before merging" banner at the top so a
    # contributor can't accidentally ship the un-authored skeleton.
    out = out.replace(
        f"# {title}",
        f"# {title}\n\n> ⚠️ **STUB — generated by `scripts/specify_new_feature.py` "
        f"on {today}. Replace every `<…>` placeholder with real content. "
        f"DO NOT MERGE until §1-§5 are written and the conformance test passes.**",
        1,  # only the first occurrence
    )
    return out


def render_conformance_stub(number: int, name_kebab: str) -> str:
    """Build a failing-stub conformance test that imports cleanly."""
    name_snake = kebab_to_snake(name_kebab)
    title = kebab_to_title(name_kebab)
    today = date.today().isoformat()
    return f'''"""Conformance test: skill {number:02d} — {title}.

STUB generated by ``scripts/specify_new_feature.py`` on {today}.

The intent of a conformance test is to pin the SKILL's documented
behavior against the live implementation. Replace each
``NotImplementedError`` below with a real assertion that ties to a
specific section of the skill (e.g. "Skill {number:02d} §2 says
``foo == bar`` for delta=0.30").

Until you fill these in, ``pytest tests/conformance/`` will flunk.
That's intentional — it forces the spec to be authored BEFORE any
code is written.
"""

from __future__ import annotations

import pytest


def test_skill_{number:02d}_documented_math_matches_implementation() -> None:
    """Skill {number:02d} §2 — replace with the documented formula assertion."""
    # Example pattern:
    #
    #     from trading_agent.your_module import your_function
    #     assert your_function(0.3, 0.1) == pytest.approx(0.33)
    #
    raise NotImplementedError(
        "Skill {number:02d} stub — fill in the conformance assertion "
        "before merging. See tests/conformance/README.md for the pattern."
    )


def test_skill_{number:02d}_edge_cases() -> None:
    """Skill {number:02d} §4 — replace with the documented edge-case assertions."""
    raise NotImplementedError(
        "Skill {number:02d} stub — pin each §4 edge case to an assertion."
    )
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("name", help="kebab-case feature name (e.g. 'rsi-strategy-gate')")
    parser.add_argument("--group", default="strategy",
                        choices=sorted(VALID_GROUPS),
                        help="skill group (default: strategy)")
    parser.add_argument("--number", type=int,
                        help="explicit skill number (auto-pick if omitted)")
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would be created without writing files")
    args = parser.parse_args()

    if not re.match(r"^[a-z][a-z0-9-]*$", args.name):
        print("ERR  feature name must be lowercase kebab-case "
              "(letters, digits, hyphens; start with a letter)",
              file=sys.stderr)
        return 2

    if args.number is not None:
        number = args.number
        if number < 0 or number > 99:
            print(f"ERR  skill number must be 0-99, got {number}", file=sys.stderr)
            return 2
        # Check it's not taken.
        existing = list(SKILLS_DIR.glob(f"{number:02d}_*.md"))
        if existing:
            print(f"ERR  skill {number:02d} already exists: {existing[0].name}",
                  file=sys.stderr)
            return 2
    else:
        number = next_free_number()

    name_snake = kebab_to_snake(args.name)
    skill_filename = f"{number:02d}_{name_snake}.md"
    test_filename = f"test_skill_{number:02d}_{name_snake}.py"
    skill_path = SKILLS_DIR / skill_filename
    test_path = CONFORMANCE_DIR / test_filename

    if skill_path.exists():
        print(f"ERR  {skill_path.relative_to(REPO_ROOT)} already exists",
              file=sys.stderr)
        return 2
    if test_path.exists():
        print(f"ERR  {test_path.relative_to(REPO_ROOT)} already exists",
              file=sys.stderr)
        return 2

    skill_content = render_skill_stub(number, args.name, args.group)
    test_content = render_conformance_stub(number, args.name)

    if args.dry_run:
        print(f"[dry-run] Would create:")
        print(f"  - {skill_path.relative_to(REPO_ROOT)} ({len(skill_content):,} bytes)")
        print(f"  - {test_path.relative_to(REPO_ROOT)} ({len(test_content):,} bytes)")
        return 0

    skill_path.write_text(skill_content, encoding="utf-8")
    test_path.write_text(test_content, encoding="utf-8")

    print(f"Created skill {number:02d}: {args.name}")
    print(f"  ✓ {skill_path.relative_to(REPO_ROOT)}")
    print(f"  ✓ {test_path.relative_to(REPO_ROOT)}")
    print()
    print(f"Next steps:")
    print(f"  1. Edit {skill_path.relative_to(REPO_ROOT)}:")
    print(f"     - §1 Theory  — why this concept exists, what problem it solves")
    print(f"     - §2 Math    — the formula, with units + ranges")
    print(f"     - §3 Reference Python — WRITE LATER, after the code lands")
    print(f"     - §4 Edge cases — failure modes + how each is handled")
    print(f"     - §5 Cross-refs — related skills")
    print(f"  2. Edit {test_path.relative_to(REPO_ROOT)}:")
    print(f"     - Replace each NotImplementedError with a real assertion")
    print(f"     - The tests should FLUNK before you write any code")
    print(f"  3. Write the code that makes the conformance test pass")
    print(f"  4. Fill §3 of the skill with verbatim quotes from the code")
    print(f"  5. Update docs/skills/README.md to add the new row")
    print(f"  6. Run:")
    print(f"     python scripts/checks/build_traceability.py")
    print(f"     python scripts/checks/scan_skill_freshness.py")
    print(f"     python scripts/checks/scan_skill_quotes_match.py")
    print(f"     python scripts/checks/scan_invariant_check.py")
    print(f"     pytest tests/conformance/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
